// @ts-ignore
import ysFixWebmDuration from 'fix-webm-duration';

/**
 * Accurately parses EBML headers and appends correct duration and timecode metadata
 * to WebM blobs generated by browser MediaRecorder.
 * Ensures the exported video file has exact duration and seekability across all video players.
 */
export const fixWebmDuration = async (blob: Blob, durationMs: number): Promise<Blob> => {
  if (!blob || blob.size === 0 || durationMs <= 0) return blob;
  try {
    const fixedBlob: Blob = await new Promise((resolve) => {
      try {
        ysFixWebmDuration(blob, durationMs, (result: Blob) => {
          resolve(result || blob);
        }, { logger: false });
      } catch (e) {
        console.warn('ysFixWebmDuration synchronous error:', e);
        resolve(blob);
      }
    });
    return fixedBlob || blob;
  } catch (err) {
    console.warn('fixWebmDuration error fallback:', err);
    return blob;
  }
};
